test: Sales invoice creation
frappe/erpnext_ui_tests pull request #6
Opened 2022-03-23 12:49 UTC by nidhipurohit11

This Test - 

- Creates masters required for sales invoice creation i.e. - Creates item, customer, and sales order first,
- From the created sales order, it creates a sales invoice - Saves and submits the form,
- Validate fields of the created sales invoice.

2022-03-24 12:50 UTC, ankush requested changes

2022-03-24 12:50 UTC, ankush commented on cypress/integration/test_create_sales_invoice.js
> +		cy.click_listview_row_item(0);
```suggestion

```

These two are dependent tests 😅

2022-03-24 12:50 UTC, ankush commented on cypress/integration/test_create_sales_invoice.js
> +	it('Create Item', () => {
This item + customer creation are not tests but fixtures required for upcoming tests, these should be part of `before`.

2022-04-22 04:58 UTC, nidhipurohit11 commented on cypress/integration/test_create_sales_invoice.js
> +		cy.click_listview_row_item(0);
Done

2022-04-22 04:58 UTC, closed without merging